kind: pipeline
name: default

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: lp12.rpiambulance.com
      username:
        from_secret: SSH_USERNAME
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /home/dan/docker-compose.yml up -d at-channel
