kind: pipeline
name: deploy_at-channel

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: lp12.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - export DOCKER_HOST=127.0.0.1
        - docker-compose -f /drone/docker-compose.yml up -d at-channel
